Updated alot of programs to be mor interactive

diff --git a/Gits/check_gits b/Gits/check_gits
--- a/Gits/check_gits
+++ b/Gits/check_gits
@@ -1,18 +1,27 @@
 #!/usr/bin/env bash
 set -eo pipefail
-gits_dir=$HOME"/Gits"
-## the "--header-first" flag may not work on some systems ##
-if [ -d "$gits_dir" ] ; then
-    echo "Directory %s found in Path" 
-    pushd $gits_dir
-    diff_gits="$(exa $gits_dir | fzf --prompt="Open : " --border --margin=5% --color=dark --height=100% --reverse --header=" BOOKMARKS " --header-first)"
-    if [[ $diff_gits ]]
-    then
-        cd $gits_dir"/"$diff_gits && echo $diff_gits && git remote update && git status -uno
+while true;
+do
+    gits_dir=$HOME"/Gits"
+    if [ -d "$gits_dir" ] ; then
+        echo "Directory %s found in Path" 
+        pushd $gits_dir
+        diff_gits="$(exa $gits_dir | fzf --prompt="Open : " --border --margin=5% --color=dark --height=100% --reverse --header=" BOOKMARKS " --header-first)"
+        if [[ $diff_gits ]]
+        then
+            cd $gits_dir"/"$diff_gits && echo $diff_gits && git remote update && git status -uno
+        else
+            popd
+            exit 1
+        fi
+        popd
+        exit 1
     else
-        exit
+        echo "Directory ~/Gits is not found in Path"
+        popd
+        exit 1
     fi
-    popd
-else
-    echo "Directory ~/Gits is not found in Path"
-fi
+done
+popd
+sleep 1
+exit
diff --git a/Gits/update_gits b/Gits/update_gits
--- a/Gits/update_gits
+++ b/Gits/update_gits
@@ -1,21 +1,29 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
-gits_dir=$HOME"/Gits"
-pushd $gits_dir
-if [ -d "$gits_dir" ] ; then
-    echo "Directory $gits_dir found in Path" 
+while true;
+do
+    gits_dir=$HOME"/Gits"
     pushd $gits_dir
-## the "--header-first" flag may not work on some systems ##
-    diff_gits="$(exa $gits_dir | fzf --prompt="Upgrade : " --border --margin=5% --color=dark --height=100% --reverse --header=" Gits " --header-first)"
-    if [ "$diff_gits" = "alacritty" ]; then
-        cd "$diff_gits" && git pull --no-rebase && cargo build --release && cd ..
-    elif [[ $diff_gits ]]; then
-        cd "$diff_gits" && git pull --no-rebase && sudo make install && cd ..
-    else
+    if [ -d "$gits_dir" ] ; then
+        echo "Directory $gits_dir found in Path" 
+        pushd $gits_dir
+        diff_gits="$(exa $gits_dir | fzf --prompt="Upgrade : " --border --margin=5% --color=dark --height=100% --reverse --header=" Gits " --header-first)"
+        if [ "$diff_gits" = "alacritty" ]; then
+            cd "$diff_gits" && git pull --no-rebase && cargo build --release && cd ..
+        elif [[ $diff_gits ]]; then
+            cd "$diff_gits" && git pull --no-rebase && sudo make install && cd ..
+        else
+            popd
+            exit
+        fi
         exit
+    else
+        echo "Directory ~/Gits is not found in Path"
+        exit 1
+        
     fi
-    popd
-else
-    echo "Directory ~/Gits is not found in Path"
-fi
+done
+popd
+sleep 1
+exit
